variable "name" {}
variable "location" {}
variable "resource_group_name" {}
variable "size" {}
variable "admin_username" {}
variable "admin_password" {}
variable "disable_password_authentication" {}
variable "network_interface_ids" {}
variable "caching" {}
variable "storage_account_type" {}
variable "publisher" {}
variable "offer" {}
variable "sku" {}
variable "vm_version" {}